#!/bin/bash

####
## Wireguard must be up and connected for tinyproxy_configure to work
# Start wiregaurd using script from base image
/scripts/run
# Command taken from base image Dockerfile
/scripts/healthcheck.sh || exit 1


####
## Configure and start Tinyproxy
# Writes the Tinyproxy config to '/etc/tinyproxy/tinyproxy.conf'
/scripts/tinyproxy_configure.sh
# Start tinyproxy
tinyproxy
